### ISSUE TITLE
psql cannot connect to server

### ISSUE THREAD

**Issue by lewisj4** [jamesfacts/suite_app#11]
@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284

I am trying to navigate through our web app; however, when I search a city and click the search button I get 
`Possibly unhandled SequelizeConnectionRefusedError: connect ECONNREFUSED
    at /Users/jameslewis/WDI_Main/suite_app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:60:20
    at null.<anonymous> (/Users/jameslewis/WDI_Main/suite_app/node_modules/pg/lib/client.js:171:5)
    at emit (events.js:107:17)
    at Socket.<anonymous> (/Users/jameslewis/WDI_Main/suite_app/node_modules/pg/lib/connection.js:59:10)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickCallback (node.js:355:11)
Possibly unhandled SequelizeConnectionRefusedError: connect ECONNREFUSED
    at /Users/jameslewis/WDI_Main/suite_app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:60:20
    at null.<anonymous> (/Users/jameslewis/WDI_Main/suite_app/node_modules/pg/lib/client.js:171:5)
    at emit (events.js:107:17)
    at Socket.<anonymous> (/Users/jameslewis/WDI_Main/suite_app/node_modules/pg/lib/connection.js:59:10)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickCallback (node.js:355:11)
Possibly unhandled SequelizeConnectionRefusedError: connect ECONNREFUSED
    at /Users/jameslewis/WDI_Main/suite_app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:60:20
    at null.<anonymous> (/Users/jameslewis/WDI_Main/suite_app/node_modules/pg/lib/client.js:171:5)
    at emit (events.js:107:17)
    at Socket.<anonymous> (/Users/jameslewis/WDI_Main/suite_app/node_modules/pg/lib/connection.js:59:10)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickCallback (node.js:355:11)`

Also when I try and psql in the terminal I get
`psql: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?`

This all started around the time our group was working on pushing our web app on heroku, although I don't think that has anything to do with the problem at hand. 

As far as things I have tried to fix this, I ran npm install to see if it was a dependency issue, but I don't believe it is.

The problems all start when trying to use POSTGRES. So my questions specifically is why can I not connect to psql?

**Comment by harimohanraj89** [comment]
Closing this issue, as we installed the Postgres App!
